services:
  backend:
    container_name: backend_django
    build: 
      context: .
    volumes:
      - .:/app/
    ports:
      - 8000:8000
    env_file:
      - .env
    entrypoint: /app/entrypoint.sh
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - backend_db

  backend_db:
    container_name: backend_db
    image: postgres:latest
    env_file:
      - .env