# Generated by Django 5.0.6 on 2024-06-27 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comments', '0001_initial'),
        ('discussions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='discussion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='discussions.discussion'),
        ),
    ]
